default_language_version:
  python: python3.12
exclude: ^env/
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - sqlalchemy[mypy]
          - types-redis
          - types-python-dateutil
          - types-simplejson
          - types-requests
          - attrs
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
