default_language_version:
  python: python3.11
exclude: ^env/
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: ["sqlalchemy[mypy]", "types-redis", "types-python-dateutil"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
      - id: ruff-format
