services:
  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379"
  rabbitmq:
    image: rabbitmq:3.12
    ports:
      - "127.0.0.1:5672:5672"
  postgres:
    image: postgres:16
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: remoulade
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: remoulade
