{
 "title": "Remoulade",
 "description": "A dashboard for Remoulade, a distributed task processing library for Python.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(remoulade_worker_busy, namespace)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(rabbitmq_queue_messages{namespace=\"$namespace\"}, job)"
    }
   },
   { "name": "kibana_url", "label": "kibana url", "query": "${VAR_KIBANA_URL}" }
  ]
 },
 "panels": [
  {
   "title": "Message processing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(actor_name) (actor_name:remoulade_message_duration_milliseconds_count:increase5m{namespace=\"$namespace\", service=~\"$env-.*\"}> 0)",
     "legendFormat": "{{actor_name}}"
    }
   ]
  },
  {
   "title": "Message retries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(actor_name) (actor_name:remoulade_message_retries_total:increase5m{namespace=\"$namespace\", service=~\"$env-.*\"} > 0)",
     "legendFormat": "{{actor_name}} retried"
    },
    {
     "expr": "sum by(actor_name) (actor_name:remoulade_message_rejects_total:increase5m{namespace=\"$namespace\", service=~\"$env-.*\"}) > 0",
     "legendFormat": "{{actor_name}} failed"
    }
   ]
  },
  {
   "title": "Message processing time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (actor_name) (actor_name:remoulade_message_duration_milliseconds:mean5m{namespace=\"$namespace\", service=~\"$env-.*\"} > 0)",
     "legendFormat": "{{actor_name}}"
    }
   ]
  },
  {
   "title": "Messages per queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (queue) (rabbitmq_queue_messages{namespace=\"$namespace\", queue!~\"^.+(DQ|XQ)$\", queue!=\"wiremind_check_service\", job=~\"$env-.*\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Load tasks mean time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(actor_name) (actor_name:remoulade_message_duration_milliseconds:mean5m{namespace=\"$namespace\", service=~\"$env-.*\"} > 0)",
     "legendFormat": "{{actor_name}}"
    }
   ]
  },
  {
   "title": "Worker count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(deployment)(kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\"$env-.*-normal\", deployment!=\"$namespace-scheduler-normal\"}) > 0",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}