name: Upload Python Package

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/remoulade/
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v5
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          activate-environment: true
      - name: Install dependencies
        run: uv pip install twine
      - name: Build package
        run: |
          uv build
          twine check --strict dist/*
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
