name: validate-commit

on: push

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Commitsar check
        uses: docker://aevea/commitsar:0.20.2
