name: validate-commit

on: push

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Commitsar check
        uses: docker://aevea/commitsar:0.20.2
